### ISSUE TITLE
Scene activation does not work on RX-V475

### ISSUE THREAD

**Issue by sivoba** [codetheweb/homebridge-yamaha-scene#2] opened 2018-03-30 18:37 UTC
Switching on/off works fine, automated adjusting of the volume to the preset level works also. Unfortunately the chosen scene is not activated. Any ideas?

**Comment by codetheweb** [comment] 2018-03-31 03:07
Duplicate of #1. Honestly, because of the way I'm currently using this I'm not planning on changing it anytime soon.

However, you're more than welcome to fix it and open a pull request :). It shouldn't be too hard, just add an option for `config.json` on whether or not to consider a currently disabled scene as powered off.

**Closed as completed by codetheweb** 2018-03-31 03:07 UTC
